### ISSUE TITLE
不显示位置和国旗

### ISSUE THREAD

**Issue by catxian** [wansyu/nezha-freebsd#1]
bash <(curl -s https://raw.githubusercontent.com/k0baya/nezha4serv00/main/install-dashboard.sh)
用这个脚本安装在serv00虚拟主机上的时候，面板就没有国旗和位置
![image](https://github.com/user-attachments/assets/5a418478-b58e-462a-b1c6-68ae3a882618)
然后我去问作者，作者让我和您反馈一下
>二进制文件在构建的时候没有正确设置离线数据库导致的

**Comment by catxian** [comment]
>因为nezha的源码仓库中这个geoip的文件是空的，所以不显示。按照 nezha 的 wiki 说明，就是叫构建二进制的仓库的作者在构建时找一个 geoip.db 文件替换进去，这很好修的

佬可以修一下嘛

**Comment by wansyu** [comment]
可否提供可用的geoip.db，我试试

**Comment by k0baya** [comment]
参考源仓库的 workflow : 
https://github.com/naiba/nezha/blob/71508f8724e5736b318d33446e3cdd8b7029cd26/.github/workflows/release.yml#L20

```
          rm pkg/geoip/geoip.db
          wget -O pkg/geoip/geoip.db https://ipinfo.io/data/free/country.mmdb?token=${IPINFO_TOKEN}
```
需要您在 https://ipinfo.io/ 注册账号并获取 Token，然后在 workflow 中加入类似的步骤。

**Comment by wansyu** [comment]
我更新了

> 参考源仓库的 workflow : https://github.com/naiba/nezha/blob/71508f8724e5736b318d33446e3cdd8b7029cd26/.github/workflows/release.yml#L20
> 
> ```
>           rm pkg/geoip/geoip.db
>           wget -O pkg/geoip/geoip.db https://ipinfo.io/data/free/country.mmdb?token=${IPINFO_TOKEN}
> ```
> 
> 需要您在 https://ipinfo.io/ 注册账号并获取 Token，然后在 workflow 中加入类似的步骤。

我更新了
